"""Compatibility exports for typed internal errors."""

from ai_assistant.domain.errors import (
    AmbiguousPathError,
    AssistantError,
    ConfigurationError,
    ConversationStoreError,
    ExecutionStoreError,
    InvalidMessageError,
    InvalidSessionError,
    InvalidToolCallError,
    ModelConnectionError,
    ModelNotFoundError,
    ModelProtocolError,
    ModelTimeoutError,
    PathNotFoundError,
    PathOutsideWorkspaceError,
    PathPermissionDeniedError,
    SensitivePathError,
    ToolAuditStoreError,
    ToolPathError,
    UnsupportedFileTypeError,
)

__all__ = [
    "AmbiguousPathError",
    "AssistantError",
    "ConfigurationError",
    "ConversationStoreError",
    "ExecutionStoreError",
    "InvalidMessageError",
    "InvalidSessionError",
    "InvalidToolCallError",
    "ModelConnectionError",
    "ModelNotFoundError",
    "ModelProtocolError",
    "ModelTimeoutError",
    "PathNotFoundError",
    "PathOutsideWorkspaceError",
    "PathPermissionDeniedError",
    "SensitivePathError",
    "ToolAuditStoreError",
    "ToolPathError",
    "UnsupportedFileTypeError",
]
