"""Domain objects for the assistant core."""

from ai_assistant.domain.errors import (
    AssistantError,
    ConfigurationError,
    ConversationStoreError,
    InvalidMessageError,
    InvalidSessionError,
    InvalidToolCallError,
    ModelConnectionError,
    ModelNotFoundError,
    ModelProtocolError,
    ModelTimeoutError,
    ToolAuditStoreError,
)
from ai_assistant.domain.message import Message, Role
from ai_assistant.domain.session import DEFAULT_SESSION_ID, SessionId, validate_session_id
from ai_assistant.domain.tools import (
    PolicyDecisionKind,
    SanitizedToolError,
    ToolAuditEvent,
    ToolCall,
    ToolCallPlan,
    ToolDefinition,
    ToolExecutionContext,
    ToolExecutionRequest,
    ToolExecutionResult,
    ToolExecutionStatus,
    ToolPermission,
    ToolPolicyDecision,
)

__all__ = [
    "AssistantError",
    "ConfigurationError",
    "ConversationStoreError",
    "DEFAULT_SESSION_ID",
    "InvalidMessageError",
    "InvalidSessionError",
    "InvalidToolCallError",
    "Message",
    "ModelConnectionError",
    "ModelNotFoundError",
    "ModelProtocolError",
    "ModelTimeoutError",
    "Role",
    "PolicyDecisionKind",
    "SanitizedToolError",
    "SessionId",
    "ToolAuditEvent",
    "ToolAuditStoreError",
    "ToolCall",
    "ToolCallPlan",
    "ToolDefinition",
    "ToolExecutionContext",
    "ToolExecutionRequest",
    "ToolExecutionResult",
    "ToolExecutionStatus",
    "ToolPermission",
    "ToolPolicyDecision",
    "validate_session_id",
]
